name: ai_navigation_flutter
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  # easy_localization-hoz kell
  flutter_localizations:
    sdk: flutter

  # --- IDE KELLŐ FŐ CSOMAGOK (a build hibák miatt) ---
  easy_localization: ^3.0.7
  path_provider: ^2.1.5
  geolocator: ^12.0.0
  flutter_background_service: ^5.0.6
  flutter_local_notifications: ^17.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  shared_preferences: ^2.2.3
  flutter_tts: ^4.0.2
  sqflite: ^2.3.3
  path: ^1.9.0
  vector_map_tiles: ^3.0.0
  vector_map_tiles_pmtiles: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon/icon.png
    - assets/i18n/en.json
    - assets/i18n/hu.json
    - assets/i18n/de.json
    # - assets/maps/   # ha később lesznek térképfájlok

# --- Splash ---
flutter_native_splash:
  android: true
  ios: true
  image: assets/icon/icon.png
  color: "#ffffff"

# --- Launcher ikon ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: assets/icon/icon.png
  min_sdk_android: 24
  remove_alpha_ios: true

# Nálad már volt override ehhez a stackhez – hagyjuk így
dependency_overrides:
  vector_tile_renderer: "5.2.1"
