name: ai_navigation_flutter
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'  # <-- Javítva erre a kompatibilis verzióra
  flutter: '>=3.22.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # ikon- és splash-generátorok
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon/icon.png
    - assets/i18n/en.json
    - assets/i18n/hu.json
    - assets/i18n/de.json
    #--++terkepek helye lesz++- assets/maps/

# --- Splash beállítás ---
flutter_native_splash:
  android: true
 # ios: true
  image: assets/icon/icon.png
  color: "#ffffff"

# --- Launcher ikon beállítás ---
flutter_launcher_icons:
  android: "ic_launcher"
 # ios: true
  image_path: assets/icon/icon.png
  min_sdk_android: 24
  remove_alpha_ios: true

dependency_overrides:
  vector_tile_renderer: "5.2.1"
