name: ai_navigation_flutter
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  # easy_localization-hoz kell
  flutter_localizations:
    sdk: flutter

   # meglévők – maradhatnak
  flutter_map: ^6.2.1
  vector_map_tiles: ^7.0.0
  vector_map_tiles_pmtiles: ">=1.1.0 <2.0.0"  # <- EZ a jó csomagnév
  vector_tile_renderer: ^5.2.1   
  latlong2: ^0.9.1
  background_downloader: ^9.2.3
  path_provider: ^2.1.4
  sqflite: ^2.3.3
  shared_preferences: ^2.3.2
  flutter_tts: ^3.8.5
  easy_localization: ^3.0.5
  geolocator: ^14.0.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  collection: ^1.18.0
  path: ^1.9.0                    # <- hasznos a fájl-útvonalakhoz
  permission_handler: ^11.3.1

  # új/frissített – 5.1-es háttér + értesítés
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.0.0
  flutter_local_notifications: ^17.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # ikon- és splash-generátorok
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/ai_logo.png
    - assets/logo.png
    - assets/icon/icon.png
    - assets/i18n/en.json
    - assets/i18n/hu.json
    - assets/i18n/de.json
    # - assets/maps/   # ha később lesznek térképfájlok


# --- Splash ---
flutter_native_splash:
  android: true
  ios: false
  image: assets/icon/icon.png
  color: "#ffffff"

  # ÚJ BEÁLLÍTÁSOK ITT:
  # Ez dönti el, hogyan illeszkedik a kép.
  # "cover" vagy "fill" a teljes kitöltéshez.
  image_content_mode: "cover" 
  # Android specifikus gravitáció, ha a kép nem tölti ki teljesen
  # Csak régi Androidokon van hatása, de érdemes beállítani.
  android_gravity: "fill" # Vagy "center", "top", stb.
  
  # Android 12 és újabb rendszerekhez
  android_12:
    image: assets/icon/icon.png
    color: "#ffffff"
    # Itt is megadhatod az image_content_mode-ot,
    # de általában az Android 12 jobb alapértelmezett viselkedéssel bír
    image_content_mode: "cover" 
    # android_gravity: "fill" # Android 12-nél általában nincs rá szükség


# --- Launcher ikon ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: assets/icon/icon.png
  min_sdk_android: 24
  remove_alpha_ios: true
  
  
# Nálad már volt override ehhez a stackhez – hagyjuk így
dependency_overrides:
  vector_tile_renderer: "5.2.1"
