name: ai_navigation_flutter
description: AI Navigation app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"         # Dart 3.6 (β)
  flutter: ">=3.26.0-0"         # Flutter 3.26 beta vonal

dependencies:
  flutter:
    sdk: flutter

  # --- FLEAFLET β STACK (git ref-ekkel) ---
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
      ref: v8.2.0-beta.2
  vector_map_tiles:
    git:
      url: https://github.com/fleaflet/vector_map_tiles.git
      ref: v9.0.0-beta.2
  vector_tile_renderer:
    git:
      url: https://github.com/fleaflet/vector_tile_renderer.git
      ref: v8.0.0-beta.2
  vector_map_tiles_pmtile:
    git:
      url: https://github.com/fleaflet/vector_map_tiles_pmtile.git
      ref: v2.1.0-beta.1

  # --- a többi marad, ahogy használtad ---
  latlong2: ^0.9.1
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  background_downloader: ^8.2.3
  flutter_tts: ^4.2.3
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
