name: ai_navigation_flutter
publish_to: 'none'
description: Offline truck-first navigation (EU+UK)
version: 0.1.0+1


flutter_icons:
  android: true
  ios: true
  image_path: assets/icon-1024.png

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
