name: ai_navigation_flutter
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  # easy_localization-hoz kell
  flutter_localizations:
    sdk: flutter

   
  flutter_map: ^6.2.1
  vector_map_tiles: ^7.0.0
  vector_map_tiles_pmtiles: ">=1.1.0 <2.0.0"  
  vector_tile_renderer: ^5.2.1   
  latlong2: ^0.9.1
  background_downloader: ^9.2.3
  path_provider: ^2.1.4
  sqflite: ^2.3.3
  shared_preferences: ^2.3.2
  flutter_tts: ^3.8.5
  easy_localization: ^3.0.5
  geolocator: ^14.0.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  collection: ^1.18.0
  path: ^1.9.0                   
  permission_handler: ^11.3.1
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.0.0
  flutter_local_notifications: ^17.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # ikon- és splash-generátorok
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/ai_logo.png
    - assets/logo.png
    - assets/icon/icon.png
    - assets/i18n/en.json
    - assets/i18n/hu.json
    - assets/i18n/de.json
    # - assets/maps/   # ha később lesznek térképfájlok

# --- Splash ---
# A helyes kód a logo.png teljes képernyős megjelenítéséhez
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png

  # Beállítások régebbi Android verziókhoz
  android_gravity: fill

  # Beállítások Android 12 és újabb verziókhoz
  android_12:
    color: "#ffffff"
    image: assets/logo.png
    image_content_mode: cover

# --- Launcher ikon ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: assets/icon/icon.png
  min_sdk_android: 24
  remove_alpha_ios: true
   
# Nálad már volt override ehhez a stackhez – hagyjuk így
dependency_overrides:
  vector_tile_renderer: "5.2.1"
