name: ai_navigation_flutter
description: AI Navigation app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"
dependencies:
  latlong2: ^0.9.1
  vector_map_tiles_pmtiles:  ^2.0.0
  flutter:
    sdk: flutter
  flutter_map:  ^8.0.0
  vector_map_tiles:  ^9.0.0
  vector_tile_renderer:  ^8.0.0
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  background_downloader: ^9.2.3
  flutter_tts: ^4.2.3
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
