name: ai_navigation_flutter
publish_to: 'none'
description: Offline truck-first navigation (EU+UK)
version: 0.1.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  flutter_map: ^6.2.1
  vector_map_tiles: ^7.0.0
  vector_map_tiles_pmtiles: ^1.1.0
  latlong2: ^0.9.1
  background_downloader: ^7.12.3
  path_provider: ^2.1.4
  sqflite: ^2.3.3
  shared_preferences: ^2.3.2
  flutter_tts: ^3.8.3
  easy_localization: ^3.0.5
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  http: ^1.2.2

  # state & utils
  collection: ^1.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/hu.json
    - assets/i18n/de.json
    - assets/logo.svg

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon-1024.png   # lásd: 8) Logó → export PNG 1024x1024

