name: ai_navigation_flutter
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }

  # meglévők – maradhatnak
  flutter_map: ^6.2.1
  vector_map_tiles: ^7.0.0
  vector_map_tiles_pmtiles: ^1.1.0
  latlong2: ^0.9.1
  background_downloader: ^9.2.3
  path_provider: ^2.1.4
  sqflite: ^2.3.3
  shared_preferences: ^2.3.2
  flutter_tts: ^3.8.3
  easy_localization: ^3.0.5
  geolocator: ^14.0.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  collection: ^1.18.0

  # ÚJ/FRISSÍTETT – 5.1-es háttér + értesítés
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.0.0
  flutter_local_notifications: ^17.2.2
  workmanager: ^0.5.1-dev.7

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/ai_logo.png
    - assets/i18n/en.json
    - assets/i18n/hu.json
    - assets/i18n/de.json
    

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  android: true
  ios: true
  image_path: assets/icon/icon.png
